// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250428144412_CriacaoEstoqueProdutoHistorico")]
    partial class CriacaoEstoqueProdutoHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CWEstoque", b =>
                {
                    b.Property<int>("nCdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdEstoque"));

                    b.Property<string>("sCdCep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sCdEstoque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsComplemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsEstoque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsRua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmEstoque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNrNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdEstoque");

                    b.ToTable("ESTOQUE", (string)null);
                });

            modelBuilder.Entity("CWEstoqueProdutoHistorico", b =>
                {
                    b.Property<int>("nCdEstoqueProdutoHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdEstoqueProdutoHistorico"));

                    b.Property<int>("dQtMovimentada")
                        .HasColumnType("integer");

                    b.Property<int>("nCdEstoque")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("nCdEstoqueDestino")
                        .HasColumnType("integer");

                    b.Property<int>("nCdProduto")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("nTipoMovimentacao")
                        .HasColumnType("integer");

                    b.Property<string>("sDsObservacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("tDtMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("nCdEstoqueProdutoHistorico");

                    b.HasIndex("nCdEstoque", "nCdProduto");

                    b.ToTable("ESTOQUE_PRODUTO_HISTORICO", (string)null);
                });

            modelBuilder.Entity("CWProdutoOpcaoVariacao", b =>
                {
                    b.Property<int>("nCdProduto")
                        .HasColumnType("integer");

                    b.Property<int>("nCdVariacaoOpcao")
                        .HasColumnType("integer");

                    b.Property<int>("nCdVariacao")
                        .HasColumnType("integer");

                    b.Property<int?>("CWProdutonCdProduto")
                        .HasColumnType("integer");

                    b.HasKey("nCdProduto", "nCdVariacaoOpcao", "nCdVariacao");

                    b.HasIndex("CWProdutonCdProduto");

                    b.HasIndex("nCdVariacao");

                    b.HasIndex("nCdVariacaoOpcao");

                    b.ToTable("ProdutoOpcaoVariacao");
                });

            modelBuilder.Entity("Domain.Entities.CWEstoqueProduto", b =>
                {
                    b.Property<int>("nCdEstoque")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("nCdProduto")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<bool>("bFlAtivo")
                        .HasColumnType("boolean");

                    b.Property<int>("dQtEstoque")
                        .HasColumnType("integer");

                    b.Property<int>("dQtMinima")
                        .HasColumnType("integer");

                    b.Property<decimal>("dVlCusto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("dVlVenda")
                        .HasColumnType("numeric");

                    b.HasKey("nCdEstoque", "nCdProduto");

                    b.HasIndex("nCdProduto");

                    b.ToTable("ESTOQUE_PRODUTO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWProduto", b =>
                {
                    b.Property<int>("nCdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdProduto"));

                    b.Property<decimal>("dVlUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("dVlVenda")
                        .HasColumnType("numeric");

                    b.Property<int>("nCdUnidadeMedida")
                        .HasColumnType("integer");

                    b.Property<string>("sAltura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sCdProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sComprimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sLargura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sPeso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sUrlVideo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdProduto");

                    b.HasIndex("nCdUnidadeMedida");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWProdutoImagem", b =>
                {
                    b.Property<int>("nCdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdImagem"));

                    b.Property<int?>("CWProdutonCdProduto")
                        .HasColumnType("integer");

                    b.Property<int>("nCdProduto")
                        .HasColumnType("integer");

                    b.Property<string>("sDsCaminho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdImagem");

                    b.HasIndex("CWProdutonCdProduto");

                    b.HasIndex("nCdProduto");

                    b.ToTable("PRODUTO_IMAGEM", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWRevendedor", b =>
                {
                    b.Property<int>("nCdRevendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdRevendedor"));

                    b.Property<decimal>("dPcRevenda")
                        .HasColumnType("numeric");

                    b.Property<int?>("nCdEstoque")
                        .HasColumnType("integer");

                    b.Property<int>("nCdTipoRevendedor")
                        .HasColumnType("integer");

                    b.Property<string>("sCdCep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsComplemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsRua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmRevendedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNrCpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNrNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sTelefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdRevendedor");

                    b.HasIndex("nCdEstoque");

                    b.HasIndex("nCdTipoRevendedor");

                    b.ToTable("REVENDEDOR", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWRevendedorTipo", b =>
                {
                    b.Property<int>("nCdTipoRevendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdTipoRevendedor"));

                    b.Property<int>("bFlAtivo")
                        .HasColumnType("integer");

                    b.Property<string>("sDsTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdTipoRevendedor");

                    b.ToTable("REVENDEDOR_TIPO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWUnidadeMedida", b =>
                {
                    b.Property<int>("nCdUnidadeMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdUnidadeMedida"));

                    b.Property<int>("bFlAtivo")
                        .HasColumnType("integer");

                    b.Property<string>("sCdUnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsUnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sSgUnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdUnidadeMedida");

                    b.ToTable("UNIDADE_MEDIDA", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.CWVariacao", b =>
                {
                    b.Property<int>("nCdVariacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdVariacao"));

                    b.Property<bool>("bFlAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("sDsVariacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmVariacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdVariacao");

                    b.ToTable("VARIACAO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWVariacaoOpcao", b =>
                {
                    b.Property<int>("nCdVariacaoOpcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdVariacaoOpcao"));

                    b.Property<bool>("bFlAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("sDsVariacaoOpcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmVariacaoOpcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdVariacaoOpcao");

                    b.ToTable("VARIACAO_OPCAO", (string)null);
                });

            modelBuilder.Entity("VARIACAO_OPCAO_VARIACAO", b =>
                {
                    b.Property<int>("nCdVariacao")
                        .HasColumnType("integer");

                    b.Property<int>("nCdVariacaoOpcao")
                        .HasColumnType("integer");

                    b.HasKey("nCdVariacao", "nCdVariacaoOpcao");

                    b.HasIndex("nCdVariacaoOpcao");

                    b.ToTable("VARIACAO_OPCAO_VARIACAO");
                });

            modelBuilder.Entity("CWEstoqueProdutoHistorico", b =>
                {
                    b.HasOne("Domain.Entities.CWEstoqueProduto", null)
                        .WithMany("Historicos")
                        .HasForeignKey("nCdEstoque", "nCdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CWProdutoOpcaoVariacao", b =>
                {
                    b.HasOne("Domain.Entities.CWProduto", null)
                        .WithMany("OpcoesVariacoes")
                        .HasForeignKey("CWProdutonCdProduto");

                    b.HasOne("Domain.Entities.CWProduto", null)
                        .WithMany()
                        .HasForeignKey("nCdProduto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.CWVariacao", null)
                        .WithMany()
                        .HasForeignKey("nCdVariacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWVariacaoOpcao", null)
                        .WithMany()
                        .HasForeignKey("nCdVariacaoOpcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CWEstoqueProduto", b =>
                {
                    b.HasOne("CWEstoque", "Estoque")
                        .WithMany("Produtos")
                        .HasForeignKey("nCdEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWProduto", "Produto")
                        .WithMany()
                        .HasForeignKey("nCdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Domain.Entities.CWProduto", b =>
                {
                    b.HasOne("Domain.Entities.CWUnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("nCdUnidadeMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Domain.Entities.CWProdutoImagem", b =>
                {
                    b.HasOne("Domain.Entities.CWProduto", null)
                        .WithMany("Imagens")
                        .HasForeignKey("CWProdutonCdProduto");

                    b.HasOne("Domain.Entities.CWProduto", null)
                        .WithMany()
                        .HasForeignKey("nCdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CWRevendedor", b =>
                {
                    b.HasOne("CWEstoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("nCdEstoque")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.CWRevendedorTipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("nCdTipoRevendedor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("VARIACAO_OPCAO_VARIACAO", b =>
                {
                    b.HasOne("Domain.Entities.CWVariacao", null)
                        .WithMany()
                        .HasForeignKey("nCdVariacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWVariacaoOpcao", null)
                        .WithMany()
                        .HasForeignKey("nCdVariacaoOpcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CWEstoque", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Domain.Entities.CWEstoqueProduto", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Domain.Entities.CWProduto", b =>
                {
                    b.Navigation("Imagens");

                    b.Navigation("OpcoesVariacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
